# Generated by Django 4.2 on 2024-12-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadPesquera',
            fields=[
                ('codigo_actividad', models.CharField(db_column='CodigoActividad', max_length=100, primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField(db_column='FechaSalida')),
                ('puerto_salida', models.CharField(db_column='PuertoSalida', max_length=100)),
                ('fecha_entrada', models.DateField(db_column='FechaEntrada')),
                ('puerto_entrada', models.CharField(db_column='PuertoEntrada', max_length=100)),
                ('nombre_armador', models.CharField(db_column='NombreArmador', max_length=100)),
                ('nombre_capitan', models.CharField(db_column='NombreCapitan', max_length=100)),
                ('nombre_embarcacion', models.CharField(db_column='NombreEmbarcacion', max_length=100)),
                ('matricula', models.CharField(db_column='Matricula', max_length=50)),
                ('observador', models.CharField(db_column='Observador', max_length=100)),
                ('pesca_objetivo', models.CharField(db_column='PescaObjetivo', max_length=50)),
                ('arte_pesca', models.CharField(choices=[('Cerco', 'Cerco'), ('Palangre', 'Palangre'), ('Arrastre', 'Arrastre')], db_column='ArtePesca', max_length=20)),
            ],
            options={
                'db_table': 'actividadpesquera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('codigo_avistamiento', models.AutoField(db_column='Codigo_Avistamiento', primary_key=True, serialize=False)),
                ('grupos_avi_int', models.CharField(db_column='Grupos_Avi_Int', max_length=100)),
                ('nombre_cientifico', models.CharField(db_column='Nombre_Cientifico', max_length=150)),
                ('alimentandose', models.IntegerField(db_column='Alimentandose')),
                ('deambulando', models.IntegerField(db_column='Deambulando')),
                ('en_reposo', models.IntegerField(db_column='En_Reposo')),
                ('total_individuos', models.IntegerField(db_column='Total_Individuos')),
            ],
            options={
                'db_table': 'avistamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatosCaptura',
            fields=[
                ('codigo_captura', models.AutoField(db_column='Codigo_Captura', primary_key=True, serialize=False)),
                ('taxa', models.CharField(db_column='Taxa', max_length=100)),
                ('genero', models.CharField(db_column='Genero', max_length=100)),
                ('especie', models.CharField(db_column='Especie', max_length=100)),
                ('nombre_cientifico', models.CharField(db_column='Nombre_Cientifico', max_length=150)),
                ('nombre_comun', models.CharField(db_column='Nombre_Comun', max_length=150)),
                ('individuos_retenidos', models.IntegerField(db_column='Individuos_Retenidos')),
                ('individuos_descarte', models.IntegerField(db_column='Individuos_Descarte')),
                ('total_individuos', models.IntegerField(db_column='Total_Individuos')),
                ('peso_retenido', models.DecimalField(db_column='Peso_Retenido', decimal_places=2, max_digits=10)),
                ('peso_descarte', models.DecimalField(db_column='Peso_Descarte', decimal_places=2, max_digits=10)),
                ('total_peso_lb', models.DecimalField(db_column='Total_Peso_Lb', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'datos_captura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('codigo_incidencia', models.CharField(db_column='Codigo_Incidencia', max_length=50, primary_key=True, serialize=False)),
                ('grupos_avi_int', models.CharField(db_column='Grupos_Avi_Int', max_length=100)),
                ('nombre_cientifico', models.CharField(db_column='Nombre_Cientifico', max_length=150)),
                ('herida_grave', models.IntegerField(db_column='Herida_Grave')),
                ('herida_leve', models.IntegerField(db_column='Herida_Leve')),
                ('muerto', models.IntegerField(db_column='Muerto')),
                ('aves_pico', models.IntegerField(blank=True, db_column='Aves_Pico', null=True)),
                ('aves_patas', models.IntegerField(blank=True, db_column='Aves_Patas', null=True)),
                ('aves_alas', models.IntegerField(blank=True, db_column='Aves_Alas', null=True)),
                ('mamiferos_hocico', models.IntegerField(blank=True, db_column='Mamiferos_Hocico', null=True)),
                ('mamiferos_cuello', models.IntegerField(blank=True, db_column='Mamiferos_Cuello', null=True)),
                ('mamiferos_cuerpo', models.IntegerField(blank=True, db_column='Mamiferos_Cuerpo', null=True)),
                ('tortugas_pico', models.IntegerField(blank=True, db_column='Tortugas_Pico', null=True)),
                ('tortugas_cuerpo', models.IntegerField(blank=True, db_column='Tortugas_Cuerpo', null=True)),
                ('tortugas_aleta', models.IntegerField(blank=True, db_column='Tortugas_Aleta', null=True)),
                ('palangre_orinque', models.IntegerField(blank=True, db_column='Palangre_Orinque', null=True)),
                ('palangre_reinal', models.IntegerField(blank=True, db_column='Palangre_Reinal', null=True)),
                ('palangre_anzuelo', models.IntegerField(blank=True, db_column='Palangre_Anzuelo', null=True)),
                ('palangre_linea_madre', models.IntegerField(blank=True, db_column='Palangre_Linea_Madre', null=True)),
                ('total_individuos', models.IntegerField(db_column='Total_Individuos')),
                ('observacion', models.CharField(blank=True, db_column='Observacion', max_length=250, null=True)),
            ],
            options={
                'db_table': 'incidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('codigo_lance', models.CharField(db_column='CodigoLance', max_length=100, primary_key=True, serialize=False)),
                ('numero_lance', models.IntegerField(db_column='NumeroLance')),
                ('calado_fecha', models.DateField(db_column='CaladoFecha')),
                ('calado_hora', models.TimeField(db_column='CaladoHora')),
                ('latitud_ns', models.CharField(blank=True, db_column='Latitud_NS', max_length=1, null=True)),
                ('latitud_grados', models.IntegerField(blank=True, db_column='Latitud_Grados', null=True)),
                ('latitud_minutos', models.DecimalField(blank=True, db_column='Latitud_Minutos', decimal_places=3, max_digits=5, null=True)),
                ('longitud_w', models.CharField(blank=True, db_column='Longitud_W', max_length=1, null=True)),
                ('longitud_grados', models.IntegerField(blank=True, db_column='Longitud_Grados', null=True)),
                ('longitud_minutos', models.DecimalField(blank=True, db_column='Longitud_Minutos', decimal_places=3, max_digits=5, null=True)),
                ('profundidad_suelo_marino', models.DecimalField(db_column='ProfundidadSueloMarino', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'lance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanceArrastre',
            fields=[
                ('codigo_lance', models.OneToOneField(db_column='CodigoLance', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_Pesca.lance')),
                ('ted', models.BooleanField(db_column='TED')),
                ('copo', models.IntegerField(blank=True, db_column='Copo', null=True)),
                ('tunel', models.IntegerField(blank=True, db_column='Tunel', null=True)),
                ('pico', models.IntegerField(blank=True, db_column='Pico', null=True)),
            ],
            options={
                'db_table': 'lancearrastre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanceCerco',
            fields=[
                ('codigo_lance', models.OneToOneField(db_column='CodigoLance', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_Pesca.lance')),
                ('altura_red', models.DecimalField(db_column='AlturaRed', decimal_places=2, max_digits=7)),
                ('longitud_red', models.DecimalField(db_column='LongitudRed', decimal_places=2, max_digits=7)),
                ('malla_cabecero', models.DecimalField(db_column='MallaCabecero', decimal_places=2, max_digits=5)),
                ('malla_cuerpo', models.DecimalField(db_column='MallaCuerpo', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'lancecerco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LancePalangre',
            fields=[
                ('codigo_lance', models.OneToOneField(db_column='CodigoLance', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_Pesca.lance')),
                ('carnada1', models.CharField(blank=True, db_column='Carnada1', max_length=100, null=True)),
                ('porcentaje_carnada1', models.DecimalField(blank=True, db_column='PorcentajeCarnada1', decimal_places=2, max_digits=5, null=True)),
                ('carnada2', models.CharField(blank=True, db_column='Carnada2', max_length=100, null=True)),
                ('porcentaje_carnada2', models.DecimalField(blank=True, db_column='PorcentajeCarnada2', decimal_places=2, max_digits=5, null=True)),
                ('tipo_anzuelo', models.CharField(blank=True, db_column='TipoAnzuelo', max_length=50, null=True)),
                ('tamano_anzuelo', models.DecimalField(blank=True, db_column='TamanoAnzuelo', decimal_places=2, max_digits=5, null=True)),
                ('cantidad_anzuelos', models.IntegerField(blank=True, db_column='CantidadAnzuelos', null=True)),
                ('linea_madre_metros', models.DecimalField(blank=True, db_column='LineaMadreMetros', decimal_places=2, max_digits=7, null=True)),
                ('profundidad_anzuelo_metros', models.DecimalField(blank=True, db_column='ProfundidadAnzueloMetros', decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'lancepalangre',
                'managed': False,
            },
        ),
    ]
