# Generated by Django 4.2 on 2024-12-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pesca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenciaaves',
            name='herida_grave',
        ),
        migrations.RemoveField(
            model_name='incidenciaaves',
            name='herida_leve',
        ),
        migrations.RemoveField(
            model_name='incidenciaaves',
            name='muerto',
        ),
        migrations.RemoveField(
            model_name='incidenciamamiferos',
            name='herida_grave',
        ),
        migrations.RemoveField(
            model_name='incidenciamamiferos',
            name='herida_leve',
        ),
        migrations.RemoveField(
            model_name='incidenciamamiferos',
            name='muerto',
        ),
        migrations.RemoveField(
            model_name='incidenciatortugas',
            name='herida_grave',
        ),
        migrations.RemoveField(
            model_name='incidenciatortugas',
            name='herida_leve',
        ),
        migrations.RemoveField(
            model_name='incidenciatortugas',
            name='muerto',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='Totalindividuos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='herida_grave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='herida_leve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='muerto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='codigo_coordenadas',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='latitud_grados',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='latitud_minutos',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='longitud_grados',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='longitud_minutos',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='codigo_embarcacion',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='especie',
            name='codigo_especie',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='codigo_persona',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='codigo_puerto',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
