# Generated by Django 4.2 on 2024-12-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pesca', '0002_remove_incidenciaaves_herida_grave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadas',
            name='latitud_grados',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='latitud_minutos',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='longitud_grados',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='longitud_minutos',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
