# Generated by Django 4.2 on 2024-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pesca', '0003_alter_coordenadas_latitud_grados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadas',
            name='latitud_grados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='longitud_grados',
            field=models.IntegerField(default=0),
        ),
    ]
