# Generated by Django 4.2 on 2024-12-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pesca', '0004_alter_coordenadas_latitud_grados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puerto',
            name='nombre_puerto',
            field=models.CharField(default='Sin nombre', max_length=100, unique=True),
        ),
    ]
