# Generated by Django 4.2 on 2024-12-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pesca', '0005_alter_puerto_nombre_puerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancepalangre',
            name='Tipo',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
