# Generated by Django 4.2 on 2025-01-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_grupo_remove_especie_grupos_especie_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
