# Generated by Django 4.2 on 2025-01-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_remove_especie_grupo_delete_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avistamiento',
            name='codigo_avistamiento',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datoscaptura',
            name='codigo_captura',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lance',
            name='codigo_lance',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
